# Generated by Django 2.1.3 on 2018-11-18 21:55

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='date_added',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='category',
            name='category_name',
            field=models.CharField(max_length=264, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='priority',
            field=models.IntegerField(default=1),
        ),
    ]
