# Generated by Django 2.1.3 on 2018-11-21 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0002_auto_20181118_2255'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
