# Generated by Django 2.1.3 on 2018-11-23 11:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0003_userprofile_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='category',
            new_name='i_category',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='title',
            new_name='i_title',
        ),
        migrations.RemoveField(
            model_name='idea',
            name='date_added',
        ),
        migrations.AddField(
            model_name='idea',
            name='i_auction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='idea',
            name='i_buyer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buyer', to='idea_app.UserProfile'),
        ),
        migrations.AddField(
            model_name='idea',
            name='i_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='seller', to='idea_app.UserProfile'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='i_date_added',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='i_description',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='i_dislikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='i_likes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='idea',
            name='i_picture',
            field=models.ImageField(blank=True, upload_to='idea_pictures'),
        ),
        migrations.AddField(
            model_name='idea',
            name='i_price',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='idea',
            name='i_status',
            field=models.BooleanField(default=True),
        ),
    ]
