# Generated by Django 2.1.3 on 2018-11-25 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0004_auto_20181123_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='idea',
            name='i_picture',
        ),
    ]
