# Generated by Django 2.1.3 on 2018-11-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0005_remove_idea_i_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='i_date_sold',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
