# Generated by Django 2.1.3 on 2018-11-25 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0006_idea_i_date_sold'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='i_status',
            new_name='i_is_active',
        ),
    ]
