# Generated by Django 2.1.3 on 2018-11-29 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0008_auto_20181126_0058'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='i_file',
            field=models.FileField(blank=True, upload_to='idea_files'),
        ),
    ]
