# Generated by Django 2.1.3 on 2018-11-30 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0009_idea_i_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='idea',
            name='i_content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='idea',
            name='i_file',
            field=models.FileField(blank=True, null=True, upload_to='idea_files'),
        ),
    ]
