# Generated by Django 2.1.3 on 2018-11-30 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0010_auto_20181130_1752'),
    ]

    operations = [
        migrations.RenameField(
            model_name='idea',
            old_name='i_auction_end',
            new_name='auction_end',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_buyer',
            new_name='buyer',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_category',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_content',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_creator',
            new_name='creator',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_date_added',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_date_sold',
            new_name='date_sold',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_dislikes',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_file',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_is_auction',
            new_name='is_auction',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_is_active',
            new_name='is_public',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_likes',
            new_name='likes',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_price',
            new_name='price',
        ),
        migrations.RenameField(
            model_name='idea',
            old_name='i_title',
            new_name='title',
        ),
    ]
