# Generated by Django 2.1.3 on 2018-12-01 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0011_auto_20181130_1814'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaAssessment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_positive', models.BooleanField()),
                ('idea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea_app.Idea')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='idea_app.UserProfile')),
            ],
        ),
    ]
