# Generated by Django 2.1.3 on 2018-12-01 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0012_ideaassessment'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IdeaAssessment',
            new_name='IdeaRating',
        ),
    ]
