# Generated by Django 2.1.3 on 2018-12-01 14:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idea_app', '0013_auto_20181201_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='idearating',
            name='idea',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idea', to='idea_app.Idea'),
        ),
        migrations.AlterField(
            model_name='idearating',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_giver', to='idea_app.UserProfile'),
        ),
    ]
